apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-services.fullname" . }}
  labels:
    {{- include "k8s-services.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8s-services.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-services.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-services.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainer.enable | default false}}
      initContainers:
        - name: "init{{ .Release.Name }}"
          command:
              {{- toYaml .Values.initContainer.command | nindent 12 }}
          env:
              {{- toYaml .Values.env | nindent 12 }}
          securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
              {{- toYaml .Values.resources | nindent 12 }}
          {{- if or (.Values.configsPath) (.Values.pvc.enable) (.Values.emptyDir.enable)}}
          volumeMounts:
          {{- if .Values.emptyDir.enable }}
          - name: emptydir
            mountPath: {{ .Values.emptyDir.path }}
          {{- end }}
          {{- if .Values.pvc.enable }}
          - name: persistent
            mountPath: {{ .Values.pvc.path }}
          {{- end }}
          {{- if .Values.configsPath }}
          - name: config
            mountPath: {{ .Values.configsPath }}
            readOnly: true
          {{- end }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or (.Values.configsPath) (.Values.pvc.enable) (.Values.emptyDir.enable) }}
          volumeMounts:
          {{- if .Values.emptyDir.enable }}
            - name: emptydir
              mountPath: {{ .Values.emptyDir.path }}
          {{- end }}
          {{- if .Values.pvc.enable }}
            - name: persistent
              mountPath: {{ .Values.pvc.path }}
          {{- end }}
          {{- if .Values.configsPath }}
            - name: config
              mountPath: {{ .Values.configsPath }}
              readOnly: true
          {{- end }}
          {{- end }}
      {{- if or (.Values.configsPath) (.Values.pvc.enable) (.Values.emptyDir.enable) }}
      volumes:
        {{- if .Values.emptyDir.enable }}
        - name: emptydir
          emptyDir: {}
        {{- end }}
        {{- if .Values.pvc.enable }}
        - name: persistent
          persistentVolumeClaim:
            claimName: {{ include "k8s-services.fullname" . }}
        {{- end }}
        {{- if len .Values.configs }}
        - name: config
          configMap:
            name: {{ include "k8s-services.fullname" . }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
