apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-services.fullname" . }}
  labels:
    {{- include "k8s-services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 12 }}

  selector:
    {{- include "k8s-services.selectorLabels" . | nindent 4 }}
